# Generated by Django 4.2 on 2023-06-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='user',
        ),
        migrations.AddField(
            model_name='firmuser',
            name='professions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='firmusers.profession'),
        ),
    ]
