# Generated by Django 4.2 on 2023-06-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmusers', '0002_remove_profession_user_firmuser_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
