# Generated by Django 4.2 on 2023-06-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmusers', '0005_alter_subtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/111.jpeg', upload_to='images'),
        ),
    ]
